### ISSUE TITLE
quandl accessing yahoo data is 404

### ISSUE THREAD

**Issue by tobatha** [PacktPublishing/Python-Machine-Learning-By-Example#1]
Hi, i'm wondering if anyone noticed that in C7 with the example of pulling the data from Quandl for "YAHOO/INDEX_DJI" always gets 404 error.

**Comment by tobatha** [comment]
ok, went through their core data section, it's actually "WIKI/YHOO" instead of "YAHOO/INDEX_DJI"

**Comment by tommynkoho** [comment]
I am having the same issue. Did you fix it? if yes, how?

**Comment by tobatha** [comment]
> I am having the same issue. Did you fix it? if yes, how?

no, seems like the code for that index is no longer available or might be replaced by unknown names somehow. I have no idea

**Comment by githubce** [comment]
Hi @tobatha 

Python Machine Learning By Example - Second Edition is out now.
Please have a look for all the updated content and codes in the new book on these links:

Packt website - https://www.packtpub.com/big-data-and-business-intelligence/python-machine-learning-example-second-edition

Amazon - https://www.amazon.com/dp/1789616727

Second Edition repository link - https://github.com/PacktPublishing/Python-Machine-Learning-By-Example-Second-Edition
