### ISSUE TITLE
Coding issues

### ISSUE THREAD

**Issue by tommynkoho** [PacktPublishing/Python-Machine-Learning-By-Example#2]
Hey there. I bought the book and I am currently reading it. I am having an issue with the following code:

symbol = 'YAHOO/INDEX_DJI'
start = '2001-01-01'
end = '2014-12-31'
data_raw = get_data_quandl(symbol, start, end)
data = generate_features(data_raw)
data.round(decimals=3).head(3)

data_raw is not running. It is saying that I typed the wrong quandl code.  Can you help with that?

Thanks,
Charles

**Comment by githubce** [comment]
Hi @tobatha 

Python Machine Learning By Example - Second Edition is out now.
Please have a look for all the updated content and codes in the new book on these links:

Packt website - https://www.packtpub.com/big-data-and-business-intelligence/python-machine-learning-example-second-edition

Amazon - https://www.amazon.com/dp/1789616727

Second Edition repository link - https://github.com/PacktPublishing/Python-Machine-Learning-By-Example-Second-Edition
